FROM ruby:2.2-alpine

RUN apk update && \
    apk add --no-cache \
    bash \
    git \
    build-base \
    sqlite-dev \
    openssh-client \
    libxml2-dev \
    libxml2-utils \
    libxslt \
    libxslt-dev

