source 'https://rubygems.org'
source 'https://rails-assets.org' do
  gem 'rails-assets-almond'
end

gem 'active_admin_import', '2.1.2'
gem 'activeadmin', '~> 1.0.0.pre1'
gem 'activeadmin-select2', github: 'mfairburn/activeadmin-select2'
gem 'activerecord-import'
gem 'asset_sync'
gem 'audited-activerecord', '~> 4.0'
gem 'aws-sdk', '~> 1.6'
gem 'bootstrap-sass', '~> 3.3.5'
gem 'bower-rails', '~> 0.9.2'
gem 'cancancan', '~> 1.10'
gem 'carrierwave-aws'
gem 'curb'
gem 'deep_cloneable', '~> 2.2.1'
gem 'devise'
gem 'doorkeeper'
gem 'draper'
gem 'email_validator', require: 'email_validator/strict'
gem 'flattened_active_admin'
gem 'font-awesome-rails'
gem 'google-webfonts'
gem 'htmlcompressor'
gem 'httparty'
gem 'jbuilder', '~> 2.0'
gem 'jquery-rails'
gem 'kaminari'
gem 'mini_magick'
gem 'nokogiri'
gem 'nokogumbo'
gem 'paperclip', '~> 4.3'
gem 'piet'
gem 'piet-binary'
gem 'rack-cors', require: 'rack/cors'
gem 'rails', '4.2.1'
gem 'redis-rails'
gem 'requirejs-rails'
gem 'rmagick'
gem 'rubycritic', require: false
gem 'rubyzip', '>= 1.0.0'
gem 'sass-rails', '~> 5.0'
gem 'select2-rails'
gem 'shoryuken', github: 'phstc/shoryuken', branch: 'master'
gem 'time_difference', '~> 0.4.2'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'
gem 'validates_hostname'
gem 'whois'
gem 'whois-parser'
gem 'zeroclipboard-rails'
gem 'zip-zip'

group :development do
  gem 'bullet'
  gem 'capistrano', '~> 3.4.0'
  gem 'capistrano-bundler', '~> 1.1', require: false
  gem 'capistrano-rails', '~> 1.1', require: false
  gem 'capistrano-rvm', '~> 0.1', require: false
  gem 'letter_opener'
  gem 'seed_dump'

  gem 'meta_request'

  gem 'pry-nav'
  gem 'pry-rails'
  gem 'pry-rescue'
end

group :test do
  gem 'database_cleaner'
  gem 'shoulda-matchers'
  gem 'sinatra'
  gem 'therubyracer'
  gem 'timecop'
  gem 'webmock'
end

group :staging, :production do
  gem 'newrelic_rpm'
  gem 'puma'
end

group :production, :staging, :development do
  gem 'mysql2', '~> 0.3.18'
end

group :development, :test do
  gem 'brakeman', require: false
  gem 'byebug'
  gem 'dotenv-rails'
  gem 'factory_girl_rails'
  gem 'faker'
  gem 'populator'
  gem 'rails-erd'
  gem 'rspec-mocks'
  gem 'rspec-rails', '~> 3.0'
  gem 'scientist'
  gem 'simplecov'
  gem 'spring'
  gem 'vcr'
  gem 'web-console', '~> 2.0'
end
